import React, { useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, SafeAreaView, StatusBar } from 'react-native';
import { router } from 'expo-router';
import { EmailPasswordForm } from '@/components/auth/EmailPasswordForm';
import { MagicLinkForm } from '@/components/auth/MagicLinkForm';
import { SocialButtons } from '@/components/auth/SocialButtons';
import { PhoneAuthForm } from '@/components/auth/PhoneAuthForm';
import { AuthDivider } from '@/components/auth/AuthDivider';

// This config will be generated by the setup CLI
// For now, show all auth methods
const AUTH_CONFIG = {
  providers: ['email', 'magic-link', 'google', 'apple', 'phone'] as const,
};

type AuthMethod = 'email' | 'magic-link' | 'phone';

export default function SignUpScreen() {
  const [activeMethod, setActiveMethod] = useState<AuthMethod>('email');

  const hasSocialAuth = AUTH_CONFIG.providers.includes('google') || AUTH_CONFIG.providers.includes('apple');
  const socialProviders = AUTH_CONFIG.providers.filter(p => p === 'google' || p === 'apple') as Array<'google' | 'apple'>;

  const hasMultipleMethods = AUTH_CONFIG.providers.filter(p =>
    p === 'email' || p === 'magic-link' || p === 'phone'
  ).length > 1;

  return (
    <SafeAreaView className="flex-1 bg-background">
      <StatusBar barStyle="dark-content" />

      <ScrollView className="flex-1" contentContainerStyle={{ paddingBottom: 40 }}>
        {/* Header */}
        <View className="px-6 pt-12 pb-8">
          <Text className="text-3xl font-bold text-foreground">Create account</Text>
          <Text className="mt-2 text-base text-muted-foreground">
            Get started with your free account
          </Text>
        </View>

        {/* Auth Forms */}
        <View className="px-6">
          {/* Social Auth (if enabled) */}
          {hasSocialAuth && (
            <>
              <SocialButtons providers={socialProviders} />
              <AuthDivider />
            </>
          )}

          {/* Method Switcher (if multiple methods available) */}
          {hasMultipleMethods && (
            <View className="flex-row bg-secondary rounded-lg p-1 mb-6">
              {AUTH_CONFIG.providers.includes('email') && (
                <TouchableOpacity
                  onPress={() => setActiveMethod('email')}
                  className={`flex-1 py-2 rounded-md ${
                    activeMethod === 'email' ? 'bg-background' : ''
                  }`}
                >
                  <Text
                    className={`text-center text-sm font-medium ${
                      activeMethod === 'email' ? 'text-foreground' : 'text-muted-foreground'
                    }`}
                  >
                    Email
                  </Text>
                </TouchableOpacity>
              )}

              {AUTH_CONFIG.providers.includes('magic-link') && (
                <TouchableOpacity
                  onPress={() => setActiveMethod('magic-link')}
                  className={`flex-1 py-2 rounded-md ${
                    activeMethod === 'magic-link' ? 'bg-background' : ''
                  }`}
                >
                  <Text
                    className={`text-center text-sm font-medium ${
                      activeMethod === 'magic-link' ? 'text-foreground' : 'text-muted-foreground'
                    }`}
                  >
                    Magic Link
                  </Text>
                </TouchableOpacity>
              )}

              {AUTH_CONFIG.providers.includes('phone') && (
                <TouchableOpacity
                  onPress={() => setActiveMethod('phone')}
                  className={`flex-1 py-2 rounded-md ${
                    activeMethod === 'phone' ? 'bg-background' : ''
                  }`}
                >
                  <Text
                    className={`text-center text-sm font-medium ${
                      activeMethod === 'phone' ? 'text-foreground' : 'text-muted-foreground'
                    }`}
                  >
                    Phone
                  </Text>
                </TouchableOpacity>
              )}
            </View>
          )}

          {/* Active Auth Method */}
          {activeMethod === 'email' && AUTH_CONFIG.providers.includes('email') && (
            <EmailPasswordForm mode="sign-up" />
          )}

          {activeMethod === 'magic-link' && AUTH_CONFIG.providers.includes('magic-link') && (
            <MagicLinkForm />
          )}

          {activeMethod === 'phone' && AUTH_CONFIG.providers.includes('phone') && (
            <PhoneAuthForm />
          )}

          {/* Terms and Privacy */}
          <Text className="text-xs text-muted-foreground text-center mt-6 px-4">
            By continuing, you agree to our{' '}
            <Text className="text-primary">Terms of Service</Text> and{' '}
            <Text className="text-primary">Privacy Policy</Text>
          </Text>
        </View>

        {/* Footer - Sign In Link */}
        <View className="px-6 mt-8">
          <View className="flex-row justify-center items-center">
            <Text className="text-sm text-muted-foreground">Already have an account? </Text>
            <TouchableOpacity onPress={() => router.push('/(auth)/sign-in')}>
              <Text className="text-sm font-semibold text-primary">Sign In</Text>
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
